---
- name: Create EC2 instances
  ec2_instance:
    name: "{{ instance_name }}"
    key_name: "{{ key_name }}"
    region: "{{ region_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    vpc_subnet_id: "{{ random_subnet }}"
    security_group: "{{ instance_name }}-sg"
    tags:
      Role: "synthetic-pop"
    exact_count: 1
    network:
      assign_public_ip: true
    wait: yes
    state: "running"
  register: ec2

- debug:
    msg: "{{ ec2 }}"
  
- name: Add the newly created EC2 instance(s) to the local host group
  ansible.builtin.lineinfile:  
    path="inventory/ec2"
    regexp={{ item.public_ip_address }} 
    insertafter="[synthetichost]" line="{{ item.public_ip_address }} ansible_user=ec2-user ansible_ssh_private_key_file=keys/{{ key_name }}.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
  with_items: "{{ ec2.instances }}"